export {cards}

let cards = [
{suit: "hearts", value: "ace", used: false, cardVal: "A" , imgSrc: "ace_of_hearts.png"},
{suit: "hearts", value: "2", used: false, cardVal: 2, imgSrc: "2_of_hearts.png"},
{suit: "hearts", value: "3", used: false, cardVal: 3, imgSrc: "3_of_hearts.png"},
{suit: "hearts", value: "4", used: false, cardVal: 4, imgSrc: "4_of_hearts.png"},
{suit: "hearts", value: "5", used: false, cardVal: 5, imgSrc: "5_of_hearts.png"},
{suit: "hearts", value: "6", used: false, cardVal: 6, imgSrc: "6_of_hearts.png"},
{suit: "hearts", value: "7", used: false, cardVal: 7, imgSrc: "7_of_hearts.png"},
{suit: "hearts", value: "8", used: false, cardVal: 8, imgSrc: "8_of_hearts.png"},
{suit: "hearts", value: "9", used: false, cardVal: 9, imgSrc: "9_of_hearts.png"},
{suit: "hearts", value: "10", used: false, cardVal: 10, imgSrc: "10_of_hearts.png"},
{suit: "hearts", value: "J", used: false, cardVal: 10, imgSrc: "jack_of_hearts.png"},
{suit: "hearts", value: "Q", used: false, cardVal: 10, imgSrc: "queen_of_hearts.png"},
{suit: "hearts", value: "K", used: false, cardVal: 10, imgSrc: "king_of_hearts.png"},
{suit: "clubs", value: "ace", used: false, cardVal: "A", imgSrc: "ace_of_clubs.png"},
{suit: "clubs", value: "2", used: false, cardVal: 2, imgSrc: "2_of_clubs.png"},
{suit: "clubs", value: "3", used: false, cardVal: 3, imgSrc: "3_of_clubs.png"},
{suit: "clubs", value: "4", used: false, cardVal: 4, imgSrc: "4_of_clubs.png"},
{suit: "clubs", value: "5", used: false, cardVal: 5, imgSrc: "5_of_clubs.png"},
{suit: "clubs", value: "6", used: false, cardVal: 6, imgSrc: "6_of_clubs.png"},
{suit: "clubs", value: "7", used: false, cardVal: 7, imgSrc: "7_of_clubs.png"},
{suit: "clubs", value: "8", used: false, cardVal: 8, imgSrc: "8_of_clubs.png"},
{suit: "clubs", value: "9", used: false, cardVal: 9, imgSrc: "9_of_clubs.png"},
{suit: "clubs", value: "10", used: false, cardVal: 10, imgSrc: "10_of_clubs.png"},
{suit: "clubs", value: "J", used: false, cardVal: 10, imgSrc: "jack_of_clubs.png"},
{suit: "clubs", value: "Q", used: false, cardVal: 10, imgSrc: "queen_of_clubs.png"},
{suit: "clubs", value: "K", used: false, cardVal: 10, imgSrc: "king_of_clubs.png"},
{suit: "spades", value: "ace", used: false, cardVal: "A", imgSrc: "ace_of_spades.png"},
{suit: "spades", value: "2", used: false, cardVal: 2, imgSrc: "2_of_spades.png"},
{suit: "spades", value: "3", used: false, cardVal: 3, imgSrc: "3_of_spades.png"},
{suit: "spades", value: "4", used: false, cardVal: 4, imgSrc: "4_of_spades.png"},
{suit: "spades", value: "5", used: false, cardVal: 5, imgSrc: "5_of_spades.png"},
{suit: "spades", value: "6", used: false, cardVal: 6, imgSrc: "6_of_spades.png"},
{suit: "spades", value: "7", used: false, cardVal: 7, imgSrc: "7_of_spades.png"},
{suit: "spades", value: "8", used: false, cardVal: 8, imgSrc: "8_of_spades.png"},
{suit: "spades", value: "9", used: false, cardVal: 9, imgSrc: "9_of_spades.png"},
{suit: "spades", value: "10", used: false, cardVal: 10, imgSrc: "10_of_spades.png"},
{suit: "spades", value: "J", used: false, cardVal: 10, imgSrc: "jack_of_spades.png"},
{suit: "spades", value: "Q", used: false, cardVal: 10, imgSrc: "queen_of_spades.png"},
{suit: "spades", value: "K", used: false, cardVal: 10, imgSrc: "king_of_spades.png"},
{suit: "diamonds", value: "ace", used: false, cardVal: "A", imgSrc: "ace_of_diamonds.png"},
{suit: "diamonds", value: "2", used: false, cardVal: 2, imgSrc: "2_of_diamonds.png"},
{suit: "diamonds", value: "3", used: false, cardVal: 3, imgSrc: "3_of_diamonds.png"},
{suit: "diamonds", value: "4", used: false, cardVal: 4, imgSrc: "4_of_diamonds.png"},
{suit: "diamonds", value: "5", used: false, cardVal: 5, imgSrc: "5_of_diamonds.png"},
{suit: "diamonds", value: "6", used: false, cardVal: 6, imgSrc: "6_of_diamonds.png"},
{suit: "diamonds", value: "7", used: false, cardVal: 7, imgSrc: "7_of_diamonds.png"},
{suit: "diamonds", value: "8", used: false, cardVal: 8, imgSrc: "8_of_diamonds.png"},
{suit: "diamonds", value: "9", used: false, cardVal: 9, imgSrc: "9_of_diamonds.png"},
{suit: "diamonds", value: "10", used: false, cardVal: 10, imgSrc: "10_of_diamonds.png"},
{suit: "diamonds", value: "J", used: false, cardVal: 10, imgSrc: "jack_of_diamonds.png"},
{suit: "diamonds", value: "Q", used: false, cardVal: 10, imgSrc: "queen_of_diamonds.png"},
{suit: "diamonds", value: "K", used: false, cardVal: 10, imgSrc: "king_of_diamonds.png"},
]